// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import KlarnaBoldCta from './KlarnaBoldCta';
import KlarnaFeaturedContent from './KlarnaFeaturedContent';
import KlarnaMediaCardsGrid from './KlarnaMediaCardsGrid';
import Quote from './Quote';
import Text from './Text';

export {
	Hero,
	Image,
	ImageCards,
	KlarnaBoldCta,
	KlarnaFeaturedContent,
	KlarnaMediaCardsGrid,
	Quote,
	Text,
};

export const components = {
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	bold_cta: KlarnaBoldCta,
	text_with_image: KlarnaFeaturedContent,
	klarna_media_cards_grid: KlarnaMediaCardsGrid,
	quote: Quote,
	text: Text,
};
